### ISSUE TITLE
Problem recognizing special characters

### ISSUE THREAD

**Issue by onilsson94** [EnderSyth/Genshin-Wish-Export#2]
I got this error

```
At D:\Users\olofa\Documents\Genshin-Wish-Export-main\Genshin Wish Export.ps1:22 char:36
+     2 {$langRegex= "ë¬´ê¸°|ìºë¦­í„°" }
+                                    ~~~~
Unexpected token '°" }
    3 {$langRegex= "æ­¦å™¨' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```
![image](https://user-images.githubusercontent.com/40758651/111152000-80f11480-8590-11eb-9f17-046f160cfe2d.png)

I managed to get around it by removing all languages other than english, so for me it works now just figured I should report the issue

Thanks for the awesome code btw

**Comment by EnderSyth** [comment]
Okay this should finally actually be fixed with the latest 1.3 release I just put out. I've encoded each string into Base64 and only decode when the language is selected. This should prevent anyone else from suffering in the future.

I didn't add anything new so your chopping out of the unneeded languages should work just as well. Enjoy!
